// vue_cli/15_vue-router/5_路由的props配置及replace/pages/Home.vue
<template>
    <div class="home">
        <h4>我是Home的内容</h4>
        <div>
            <ul class="nav nav-tabs">
                <li>
                    <router-link
                        replace
                        class="list-group-item"
                        to="/home/news"
                        active-class=" active"
                        >News</router-link
                    >
                </li>
                <li>
                    <router-link
                        replace
                        class="list-group-item"
                        to="/home/message"
                        active-class=" active"
                        >Message</router-link
                    >
                </li>
            </ul>
            <!-- 组件展示区 -->
            <router-view> </router-view>
        </div>
    </div>
</template>

<script>
import News from "./News";
import Message from "./Message";
export default {
    name: "Home",
    data() {
        return {};
    },
    components: {
        News,
        Message,
    },
    methods: {},
    computed: {},
    mounted() {
        // console.log(this.$route); //this.$route 为路由信息，每个路由都不同
        // console.log(this.$router); //this.$router 每个路由都有，且相同
    },
};
</script>

<style>
</style>

// my_react_cli/6_编程式路由导航，withRouter/pages/Home/index.jsx
import React, { Component } from "react"
import { Route, Redirect, Switch } from "react-router-dom"
import News from "./News"
import Message from "./Message"
import MyNavLink from "../../components/MyNavLink"
export default class index extends Component {
  render() {
    return (
      <div className="col-xs-6">
        <div className="panel">
          <div className="panel-body" style={{ width: 231 }}>
            <div>
              <h2>Home组件内容</h2>
              <div>
                <ul className="nav nav-tabs">
                  <li>
                    <MyNavLink
                      to="/home/news"
                      className="list-group-item"
                      activeClassName="active"
                    >
                      News
                    </MyNavLink>
                  </li>
                  <li>
                    <MyNavLink
                      to="/home/message"
                      className="list-group-item"
                      activeClassName="active"
                    >
                      Message
                    </MyNavLink>
                  </li>
                </ul>
                <div>
                  {/* 注册路由 */}
                  <Switch>
                    <Route path="/home/news" component={News}></Route>
                    <Route path="/home/message" component={Message}></Route>
                    <Redirect to="/home/news"></Redirect>
                  </Switch>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}
