// my_react_cli/6_编程式路由导航，withRouter/pages/Home/Message/index.jsx
import React, { Component } from "react"
import { Route, Link } from "react-router-dom"
import Detail from "./Detail"
export default class index extends Component {
  state = {
    msg: [
      { id: "001", title: "message1" },
      { id: "002", title: "message2" },
      { id: "003", title: "message3" },
    ],
  }
  replaceShow = (id, title) => {
    return () => {
      this.props.history.replace(`/Home/Message/Detail/${id}/${title}`)
    }
  }

  render() {
    console.log(this.props)
    const { msg } = this.state
    return (
      <div>
        <ul>
          {msg.map(item => {
            return (
              <li key={item.id}>
                {/* 1.params形式传参   replace模式会替换上一个路径*/}
                <Link to={`/Home/Message/Detail/${item.id}/${item.title}`} replace>
                  {item.title}
                </Link>
                <button onClick={this.replaceShow(item.id, item.title)}>replace</button>
                <button>push</button>
                {/* 2.search形式传参(类似于query传参) */}
                {/* <Link to={`/Home/Message/Detail/?id=${item.id}&title=${item.title}`}>
                  {item.title}
                </Link> */}
                {/* 3.state传参 */}
                {/* <Link
                  to={{
                    pathname: "/Home/Message/Detail",
                    state: { id: item.id, title: item.title },
                  }}
                >
                  {item.title}
                </Link> */}
              </li>
            )
          })}
        </ul>
        {/* 1.params形式传参 */}
        <Route path="/Home/Message/Detail/:id/:title" component={Detail}></Route>
        {/* 2.search形式传参 */}
        {/* <Route path="/Home/Message/Detail/" component={Detail}></Route> */}
        {/* 3.state形式传参 */}
        {/* <Route path="/Home/Message/Detail/" component={Detail}></Route> */}
      </div>
    )
  }
}

// vue_cli/15_vue-router/6_编程式路由导航(replace,push,back,forward,go)缓存/pages/Message.vue
<template>
    <div>
        <ul>
            <li v-for="item in messagesList" :key="item.id">
                <!-- 跳转路由并携带params参数，参数直接拼接上去，to的字符串写法 -->
                <!-- <router-link
                    :to="`/home/message/detail/${item.id}/${item.title}`"
                    >{{ item.title }}</router-link
                > -->
                <!-- 跳转路由并携带params参数，to的对象写法-->
                <router-link
                    :to="{
                        name: 'detail', //此时必须要用name形式
                        params: {
                            id: item.id,
                            title: item.title,
                        },
                    }"
                    >{{ item.title }}</router-link
                >
                <!-- v-for中的都能接收到其中的参数 -->
                <button @click="pushShow(item)">push查看</button>
                <button @click="pushReplace(item)">replace查看</button>
            </li>
        </ul>
        <!-- 组件展示区域 -->
        <router-view></router-view>
    </div>
</template>

<script>
export default {
    name: "Message",
    data() {
        return {
            messagesList: [
                { id: "001", title: "message001" },
                { id: "002", title: "message002" },
                { id: "003", title: "message003" },
            ],
        };
    },
    methods: {
        pushShow(item) {
            //push留历史记录
            this.$router.push({
                name: "detail",
                params: {
                    id: item.id,
                    title: item.title,
                },
            });
        },
        pushReplace(item) {
            //replace不留历史记录
            this.$router.replace({
                name: "detail",
                params: {
                    id: item.id,
                    title: item.title,
                },
            });
        },
    },
    mounted() {
        // console.log(this.$router);
        // console.log(this.$route);
    },
};
</script>

<style>
</style>
