// react/my_react_cli/5_路由传参/App.jsx
import React, { Component } from "react"
import { Route, Redirect, Switch } from "react-router-dom"
import About from "./pages/About"
import Home from "./pages/Home"
import MyNavLink from "./components/MyNavLink"
export default class app extends Component {
  render() {
    return (
      <div>
        <div className="row">
          <div className="col-xs-offset-2 col-xs-8">
            <div className="page-header">
              <h2>React Router Demo</h2>
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-xs-2 col-xs-offset-2">
            <div className="list-group">
              {/* 封装路由组件，新建一个一般组件(类似于vue中插槽)，此标签体内容也属于props */}
              <MyNavLink to="/about">About</MyNavLink>
              {/* 路由标签由Link改为NavLink， 点击时会动态追加activeClassName样式属性*/}
              <MyNavLink to="/home">Home</MyNavLink>
            </div>
          </div>
          <div className="col-xs-6">
            <div className="panel">
              <div className="panel-body">
                {/* <h3>我是About的内容</h3> */}
                {/* 注册路由 */}
                <Switch>
                  <Route path="/about" component={About}></Route>
                  <Route path="/home" component={Home}></Route>
                  {/* 重定向 */}
                  {/* 加了Switch，匹配后就不再往下匹配 */}
                  <Redirect to="/about" />
                </Switch>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

// vue_cli/15_vue-router/1_基本路由/App.vue
<template>
    <div>
        <Banner />
        <div class="row">
            <div class="col-xs-2 col-xs-offset-2">
                <div class="list-group">
                    <!-- <a class="list-group-item" href="./about.html">About</a>
                    <a class="list-group-item active" href="./home.html"
                        >Home</a
                    > -->
                    <!--  active-class="active"该元素被激活时的样式 -->
                    <!-- 借助路由实现页面跳转 -->
                    <router-link
                        class="list-group-item"
                        active-class="active"
                        to="/about"
                        >About</router-link
                    >
                    <router-link
                        class="list-group-item"
                        active-class="active"
                        to="/home"
                        >Home</router-link
                    >
                </div>
            </div>
            <div class="col-xs-6">
                <div class="panel">
                    <div class="panel-body">
                        <!-- 指定组件呈现的位置 -->
                        <router-view> </router-view>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import About from "./pages/About";
import Home from "./pages/Home";
import Banner from "./components/Banner"; //???
export default {
    name: "App",
    components: {
        About,
        Home,
        Banner,
    },
};
</script>

<style>
</style>
